nginx/docker-nginx

Dockerfile

The hkp service (port 11371) is likely to be blocked by firewalls.
To enable building of this image in a corporate environment,
http should be used instead.

Use http for PGP key download

---

Dockerfile

nginx do not support using environment variables in config files.
This PR adds ```envsubst``` to the image so it is possible to inject such variables in CMD when starting the container. It only adds about 1Mb to the image so please merge this one....
Here is an example for docker-compose:
```
web:
image: nginx
links:
- phpfpm1:php_fpm
volumes:
- ./mysite.template:/etc/nginx/conf.d/mysite.template
ports:
- "8080:80"
environment:
- NGINX_HOST=foobar.com
- NGINX_HOST_ALIAS=www.foobar.com
- NGINX_PORT=80
- NGINX_BASEDIR=/var/www
- NGINX_CLIENT_MAX_BODY_SIZE=20m
command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
```
The ```mysite.template``` file may then contain variable references like this :
```
listen …
```

Added gettext-base package to image in order to make envsubst available

---

mainline/alpine/Dockerfile
stable/alpine/Dockerfile

See also docker-library/official-images#1420.
I didn't think this was urgent enough to force you to round-trip on it again for getting https://github.com/docker-library/official-images/pull/1462 through, but wanted to get it on your radar for the next update to the image. :smile:
I also swapped `alpine` to use `:3.3` explicitly so that we don't run into any unexpected problems (for example, if 3.4 were to come out with a new version of gcc and NGINX fails to compile for whatever reason -- just to be on the safer side). :+1:

Fix "gpg" usage to stop relying on deprecated and insecure behavior

---

generate-stackbrew-library.sh
mainline/stretch-perl/Dockerfile
mainline/stretch/Dockerfile
stable/stretch-perl/Dockerfile
stable/stretch/Dockerfile

This takes advantage of the fact that http://nginx.org/packages/ includes the source packages as well, and simply compiles them on non-prebuilt architectures instead, which ensures we have a completely compatible experience with minimal maintenance overhead.
This is based heavily on https://github.com/docker-library/postgres/pull/330, and I've tried to be a little bit over-the-top on comments. :innocent:
I've personally tested all 4 builds on both `amd64` and `s390x`. :+1:

Add support for s390x via "apt-get source --compile"

---

mainline/alpine-perl/Dockerfile
mainline/alpine/Dockerfile
stable/alpine-perl/Dockerfile
stable/alpine/Dockerfile

This is the race condition that has been plaguing the official build for the past many hours, and we've found that adding "-f" helps mitigate it (doesn't completely eliminate it, but it's a dramatic improvement in the successful build ratio).

Add "-f" to GNUPGHOME deletions (helps avoid a GnuPG 2.x race condition)

---

stable/alpine-perl/Dockerfile
stable/alpine/Dockerfile
stable/buster-perl/Dockerfile
stable/buster/Dockerfile

Hi, here is a PR to upgrade to latest 1.16.x version. Let me now if you would like I reword, squash commits, whatever. Thank you :)
```
Changes with nginx 1.16.1                                        13 Aug 2019
*) Security: when using HTTP/2 a client might cause excessive memory
consumption and CPU usage (CVE-2019-9511, CVE-2019-9513,
CVE-2019-9516).
```

chore: upgrade nginx to 1.16.1

---

generate-stackbrew-library.sh

Added:
- arm32v7 for Alpine
- arm32v5 and mips64le for Debian
This could be automated with [bashbrew](https://github.com/docker-library/bashbrew).

Update supported architectures (fix #405)

---

mainline/alpine-perl/docker-entrypoint.sh
mainline/alpine/docker-entrypoint.sh
mainline/buster-perl/docker-entrypoint.sh
mainline/buster/docker-entrypoint.sh
stable/alpine-perl/docker-entrypoint.sh
stable/alpine/docker-entrypoint.sh
stable/buster-perl/docker-entrypoint.sh
stable/buster/docker-entrypoint.sh

A POSIX compatible sh is guaranteed to be available as /bin/sh. By not
using /usr/bin/env simply whitelisting /docker-entrypoint.sh within
mandatory access control frameworks, such as AppArmor, is sufficient.
When /usr/bin/env is used /docker-entrypoint.sh and the shell that
provides sh (e.g. /bin/dash for debian based images) need to be
whitelisted, increasing the possible attack area, by providing access
to a full shell.

Use /bin/sh in shebang instead of /usr/bin/env

---

mainline/alpine-perl/10-listen-on-ipv6-by-default.sh
mainline/alpine-perl/20-envsubst-on-templates.sh
mainline/alpine-perl/docker-entrypoint.sh
mainline/alpine/10-listen-on-ipv6-by-default.sh
mainline/alpine/20-envsubst-on-templates.sh
mainline/alpine/docker-entrypoint.sh
mainline/buster-perl/10-listen-on-ipv6-by-default.sh
mainline/buster-perl/20-envsubst-on-templates.sh
mainline/buster-perl/docker-entrypoint.sh
mainline/buster/10-listen-on-ipv6-by-default.sh
mainline/buster/20-envsubst-on-templates.sh
mainline/buster/docker-entrypoint.sh
stable/alpine-perl/10-listen-on-ipv6-by-default.sh
stable/alpine-perl/20-envsubst-on-templates.sh
stable/alpine-perl/docker-entrypoint.sh
stable/alpine/10-listen-on-ipv6-by-default.sh
stable/alpine/20-envsubst-on-templates.sh
stable/alpine/docker-entrypoint.sh
stable/buster-perl/10-listen-on-ipv6-by-default.sh
stable/buster-perl/20-envsubst-on-templates.sh
stable/buster-perl/docker-entrypoint.sh
stable/buster/10-listen-on-ipv6-by-default.sh
stable/buster/20-envsubst-on-templates.sh
stable/buster/docker-entrypoint.sh

**Related issue**: #421
This pull-request adds an environment variable `NGINX_ENTRYPOINT_QUIET_LOGS` to silence information messages when starting up.
By default, verbosity is identical. When this environment variable is defined, the entry point silence information messages, but keep errror messages (on stderr).

Add NGINX_ENTRYPOINT_QUIET_LOGS environment variable

---

stable/alpine-perl/Dockerfile
stable/alpine/Dockerfile
stable/buster-perl/Dockerfile
stable/buster/Dockerfile

I have a place with hard dependency on `1.18.0~2` and I couldn't use the official Nginx image before it would be updated.
I don't know for sure if it will work with your build system as I see `1.18.0~2` package available in https://nginx.org/packages/debian/ but not in https://nginx.org/packages/mainline/debian/.

Bump 1.18.0 PKG_RELEASE from 1 to 2

---

Dockerfile-debian.template
mainline/debian-perl/Dockerfile
mainline/debian/Dockerfile

`i386` packages are not built anymore for `bullseye` https://github.com/nginxinc/docker-nginx/issues/561#issuecomment-965771601

Remove i386 from packages built by upstream for Debian

---

Dockerfile-debian.template
mainline/debian-perl/Dockerfile
mainline/debian/Dockerfile
stable/debian-perl/Dockerfile
stable/debian/Dockerfile

Ref https://sks-keyservers.net/
The sks-servers.net is deprecated. Since 2021-06-21, The DNS records for the pool will no longer be provided at all.
So we shouldn't try to fetch the GPG keys from this source anymore.

Remove deprecated sks-keyservers for debian.

---

mainline/alpine-perl/Dockerfile
mainline/alpine/Dockerfile
update.sh

Alpine 3.16 was [released](https://alpinelinux.org/posts/Alpine-3.16.0-released.html) yesterday. This PR updates the `mainline` image to use the latest Alpine version.

Update mainline to Alpine 3.16

---

entrypoint/10-listen-on-ipv6-by-default.sh
entrypoint/20-envsubst-on-templates.sh
entrypoint/docker-entrypoint.sh

Although there is an open feature request to Nginx ("Add optional systemd socket activation support"
https://trac.nginx.org/nginx/ticket/237),
it's possible to use socket activation
by using the environment variable `NGINX`.
When systemd runs a socket-activated service,
systemd sets the environment variables LISTEN_FDS and LISTEN_FDNAMES for the launched process.
In docker-entrypoint.sh set NGINX from a translated LISTEN_FDS value.
For example:
LISTEN_FDS=1
translates to
NGINX=3;
LISTEN_FDS=2
translates to
NGINX=3;4;
LISTEN_FDS=3
translates to
NGINX=3;4;5;
Don't close the file descriptor 3 in the logging machinery.
Fixes #702
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>

docker-entrypoint: support socket activation

---

entrypoint/30-tune-worker-processes.sh

cgroups2 may be set in weird way:
```
$ podman run --rm --network=host debian:stable-slim sh -c 'grep cgroup /proc/self/mountinfo ; echo ; cat /proc/self/cgroup'
754 752 0:27 /../../../../../.. /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - cgroup2 cgroup2 rw,nsdelegate,memory_recursiveprot
0::/
```
add workaround for that case
Signed-off-by: Konstantin Demin <rockdrilla@gmail.com>

docker-entrypoint: 30-tune-worker-processes.sh: cgroups2 workaround

---

entrypoint/20-envsubst-on-templates.sh

Give the user the option to filter out environment variables passed to envsubt by passing `NGINX_ENVSUBST_FILTER`
closes #705

feat: add optional filter for environment variables passed to envsubst

---

mainline/alpine-perl/Dockerfile
mainline/alpine-slim/Dockerfile
mainline/alpine/Dockerfile
stable/alpine-perl/Dockerfile
stable/alpine-slim/Dockerfile
stable/alpine/Dockerfile
update.sh

Update mainline to Alpine 3.17 (see https://alpinelinux.org/posts/Alpine-3.17.0-released.html).
Requires upstream package builds to be released first.
See also https://github.com/nginxinc/docker-nginx/pull/667.

Update to Alpine 3.17

---

CODE_OF_CONDUCT.md

This adds the NGINX Code of Conduct file to the repo, as it is one of the recognized community guides by GitHub

adds the Code of Conduct file

---

Dockerfile-alpine-slim.template
Dockerfile-debian.template
entrypoint/15-local-resolvers.envsh

If enabled via NGINX_ENTRYPOINT_LOCAL_RESOLVERS variable, this script will populate NGINX_LOCAL_RESOLVERS variable that can be used in the envsubst-base templating to populate the configuration files.
Fixes https://github.com/nginxinc/docker-nginx/issues/673

Added a local resolver entrypoint script.

---

Dockerfile-alpine-perl.template
Dockerfile-alpine-slim.template
Dockerfile-alpine.template
mainline/alpine-perl/Dockerfile
mainline/alpine-slim/Dockerfile
mainline/alpine/Dockerfile
stable/alpine-perl/Dockerfile
stable/alpine-slim/Dockerfile
stable/alpine/Dockerfile

Prevent any network access e.g. apk index cache fetching.

Explicitly set no-network option for `apk del`

---

Dockerfile-alpine-perl.template
Dockerfile-alpine-slim.template
Dockerfile-alpine.template
mainline/alpine-perl/Dockerfile
mainline/alpine-slim/Dockerfile
mainline/alpine/Dockerfile
stable/alpine-perl/Dockerfile
stable/alpine-slim/Dockerfile
stable/alpine/Dockerfile

Fixes #835.
Previous to this change, $tempDir would fail to be removed since it's a directory and not a file.

Alpine: check if length of $tempDir is non-zero.

---

.test/tests/modules/run.sh
modules/Dockerfile
modules/Dockerfile.alpine
modules/README.md

In the modules examples, a `COPY` from the builder is done to ensure it's output is available to the final image. However, this operation results in the layer being part of the final image and thus slightly bloating it. 
By using a bind mount for the `RUN` operation, the builder content is exposed to this particular run operation only, in a read-only manner, and will not be part of the final image in any way.
See also https://docs.docker.com/engine/reference/builder/#run---mount.

Replace `COPY` with bind mount in modules examples

---

modules/Dockerfile
modules/Dockerfile.alpine

Update the modules/Dockerfile:
* use apt-get instead of apt in modules/Dockerfile
Do not use apt as it is meant to be an end-user tool.
* use "-o pipefail" for RUN commands in modules/Dockerfile
see:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#using-pipes
https://github.com/hadolint/hadolint/wiki/DL4006

Update modules Dockerfiles

---

.test/config.sh
.test/tests/templates-resolver-ipv6/expected-std-out.txt
.test/tests/templates-resolver-ipv6/run.sh
.test/tests/templates-resolver-ipv6/server.conf.template
entrypoint/15-local-resolvers.envsh
mainline/alpine-slim/15-local-resolvers.envsh
mainline/debian/15-local-resolvers.envsh
stable/alpine-slim/15-local-resolvers.envsh
stable/debian/15-local-resolvers.envsh

When running in IPv6 networks, the `15-local-resolvers.envsh` script will create invalid nginx configuration because the IPv6 address is not wrapped in brackets as Nginx requires. This change checks for the presence of colons (which all valid IPv6 addresses should have), and wraps the address in square brackets. `/etc/resolv.conf` syntax should never present a host and port together, so it is a valid assumption that an IPv4 nameserver configuration will never have a colon present.
This is incredibly useful for getting DNS working in IPv6 Kubernetes environments.

Add IPv6 support for local-resolvers substitution script

---

mainline/alpine-perl/Dockerfile
mainline/alpine-slim/Dockerfile
mainline/alpine/Dockerfile
mainline/debian-perl/Dockerfile
mainline/debian/Dockerfile
update.sh

Updates nginx to 1.25.4 and njs to 0.8.3.

Updated mainline nginx to 1.25.4 and njs to 0.8.3.

---

generate-stackbrew-library.sh
sync-awsecr.sh

As reported in https://github.com/nginxinc/docker-nginx/issues/869, the bookworm tags did not propagate to the AWS mirror.  This PR fixes that, and also other minor issues with the sync script such as specifying a proper architecture when pulling images since some docker runtimes can be picky about that.
Also, simplified a library generation script.

Updates to generate and sync scripts

---

Dockerfile-alpine-otel.template
Dockerfile-debian-otel.template
generate-stackbrew-library.sh
mainline/alpine-otel/Dockerfile
mainline/debian-otel/Dockerfile
update.sh

The variant provides an image built with a recently opensourced opentelemetry module developed by F5/NGINX [1].
I've decided to make a separate variant based on the main image instead of extending it because the module build-depends on a fairly large chunk of C++ code from multiple projects, which takes around 10 minutes to compile and link on an 8-core amd64 machine.  This is why it's currently limited to amd64 and arm64v8, which nginx.org provides builds for. Users can build them on less popular architectures as the instructions are still provided in the dockerfiles.
Also, it's currently only available for the "mainline" branch, with "stable" to follow in the future.
[1] https://nginx.org/en/docs/ngx_otel_module.html
[2] https://nginx.org/en/linux_packages.html#dynmodules
Before …

Added an otel module image variant.

---

stable/alpine-slim/Dockerfile
update.sh

Updates the images to use Alpine 3.19 as default version. See also https://alpinelinux.org/posts/Alpine-3.19.0-released.html.
Note: given that this requires built binaries for the new Alpine version and won't take any effect until an actual new release of `nginx` itself, this PR is intentionally marked as draft, so it can function both as a heads-up about the new release and a place that allows for subscription to any potential updates. It can then be merged later at any convenient time when everythins is ready. However, if it is still preferable to close this in the meantime, feel free to do so.

Update to Alpine 3.19

---

Dockerfile-alpine-otel.template
Dockerfile-alpine-perl.template
Dockerfile-alpine-slim.template
Dockerfile-alpine.template
Dockerfile-debian-otel.template
Dockerfile-debian-perl.template
mainline/alpine-otel/Dockerfile
mainline/alpine-perl/Dockerfile
mainline/alpine-slim/Dockerfile
mainline/alpine/Dockerfile
mainline/debian-otel/Dockerfile
mainline/debian-perl/Dockerfile
stable/alpine-perl/Dockerfile
stable/alpine-slim/Dockerfile
stable/alpine/Dockerfile
stable/debian-perl/Dockerfile

Simplify package installation in non-slim variants.
This can also be used in user images to install packages directly.

Keep repo key registered in alpine, and simplify Dockerfiles

---

Dockerfile-alpine.template
Dockerfile-debian.template
generate-stackbrew-library.sh
mainline/alpine-otel/Dockerfile
mainline/alpine-perl/Dockerfile
mainline/alpine-slim/Dockerfile
mainline/alpine/Dockerfile
mainline/debian-otel/Dockerfile
mainline/debian-perl/Dockerfile
mainline/debian/Dockerfile
stable/alpine-otel/Dockerfile
stable/alpine-perl/Dockerfile
stable/alpine-slim/Dockerfile
stable/alpine/Dockerfile
stable/debian-otel/Dockerfile
stable/debian-perl/Dockerfile
stable/debian/Dockerfile
sync-awsecr.sh
update.sh

Updated stable nginx to 1.26.0 and moved to bookworm.
This also addes otel variant for stable images.
Introduce NJS_RELEASE to hold the version for njs package release.
This is currently needed for mainline versions to pick up an update njs release (0.8.4-2).

Updates for a new stable & more

---

.test/tests/templates-resolver-ipv6/expected-std-out.txt
.test/tests/templates-resolver-ipv6/run.sh
Dockerfile-alpine-otel.template
Dockerfile-alpine-perl.template
Dockerfile-alpine-slim.template
Dockerfile-alpine.template
mainline/alpine-otel/Dockerfile
mainline/alpine-perl/Dockerfile
mainline/alpine-slim/Dockerfile
mainline/alpine/Dockerfile
stable/alpine-otel/Dockerfile
stable/alpine-perl/Dockerfile
stable/alpine-slim/Dockerfile
stable/alpine/Dockerfile

apk index no longer accepts untrusted keys since 2.14.2
pull-request-to-an-issue) here in this description (not in the title of the PR).

Fixed failure to build packages from source on recent Alpine versions

---

Dockerfile-debian.template
mainline/debian/Dockerfile
stable/debian/Dockerfile

Prebuilt binaries from nginx.org are to be signed with different keys moving forward.  This change introduces two new 4096-bit RSA keys (aptly named "signing key 2" and "signing key 3") that will be used for that process.
The keys can be fetched from nginx.org, too:
$ curl -s https://nginx.org/keys/nginx_signing.key | gpg --show-keys -
pub   rsa4096 2024-05-29 [SC]
8540A6F18833A80E9C1653A42FD21310B49F6B46
uid                      nginx signing key <signing-key-2@nginx.com>
pub   rsa2048 2011-08-19 [SC] [expires: 2027-05-24]
573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
uid                      nginx signing key <signing-key@nginx.com>
pub   rsa4096 2024-05-29 [SC]
9E9BE90EACBCDE69FE9B204CBCDCD8A38D88A2B3
uid                      nginx signing key <signing-key-3@nginx.com>
As a nice …

Updated GPG keys used to sign packages

---

Dockerfile-alpine-slim.template
Dockerfile-debian.template
mainline/alpine-otel/Dockerfile
mainline/alpine-perl/Dockerfile
mainline/alpine-slim/Dockerfile
mainline/alpine/Dockerfile
mainline/debian-otel/Dockerfile
mainline/debian-perl/Dockerfile
mainline/debian/Dockerfile
stable/alpine-otel/Dockerfile
stable/alpine-perl/Dockerfile
stable/alpine-slim/Dockerfile
stable/alpine/Dockerfile
stable/debian-otel/Dockerfile
stable/debian-perl/Dockerfile
stable/debian/Dockerfile
update.sh

This PR bumps nginx and njs to current versions.  Additionally, introduces a way to specify different dynamic modules release versions to match what's published in the repos.

Bump nginx to current versions and fix discrepancies in packaging releases

---

stable/alpine-slim/Dockerfile
update.sh

This is a follow-up to #894, given that in my eyes it seems most likely a new mainline release will precede a new stable release.
Updates the stable image to use Alpine 3.20 as default version. See also https://alpinelinux.org/posts/Alpine-3.20.0-released.html.
Note: given that this requires built binaries for the new Alpine version and won't take any effect until an actual new release of `nginx` itself, this PR is intentionally marked as draft, so it can function both as a heads-up about the new release and a place that allows for subscription to any potential updates. It can then be merged later at any convenient time when everything is ready. However, if it is still preferable to close this in the meantime, feel free to do so.
Before creating a PR, run through this checklist and mark …

Update stable to Alpine 3.20

---

generate-stackbrew-library.sh

When reviewing https://github.com/docker-library/official-images/pull/17368, I noticed it still incorrectly uses Alpine 3.19 in the generated list of tags for the new images. This is due to the commit being used to check for the Alpine version is inherited from earlier in the script, with it being the last commit that alters the Debian variant.
This PR updates the script to use the latest commit altering the Alpine (slim) image Dockerfile to correctly detect the current used Alpine version.

Use Alpine-related commit for detecting version in `generate-stackbrew-library.sh`

---

entrypoint/15-local-resolvers.envsh
mainline/alpine-slim/15-local-resolvers.envsh
mainline/debian/15-local-resolvers.envsh
stable/alpine-slim/15-local-resolvers.envsh
stable/debian/15-local-resolvers.envsh

* trailing whitespaces break configs that use quotation marks around vars. See https://github.com/nginxinc/docker-nginx-unprivileged/issues/234
Currently the awk command in `entrypoint/15-local-resolvers.envsh` will always produce a trailing whitespace.
This will break configs that make use of quotation marks around variable in config templates.
Initially opened the issue here: https://github.com/nginxinc/docker-nginx-unprivileged/issues/234

fix: remove trailing whitespace from awk command

---

modules/Dockerfile.alpine

Not all alpine-based images have curl that's needed to fetch the sources of modules built.

modules/Dockerfile.alpine: install curl

---

Dockerfile-debian-otel.template
Dockerfile-debian-perl.template
Dockerfile-debian.template
mainline/debian-otel/Dockerfile
mainline/debian-perl/Dockerfile
mainline/debian/Dockerfile
stable/debian-otel/Dockerfile
stable/debian-perl/Dockerfile
stable/debian/Dockerfile
update.sh

Similarly to what's currently happening on Alpine, use pkg-oss sources to build packages from source on Debian.  This allows us to provide fixes for architectures not covered by upstream nginx.org packages (amd64, aarch64) without touching the rest of infrastructure on nginx.org.

Use packaging sources to build packages on non-mainstream architectures.

---

Dockerfile-alpine-otel.template
Dockerfile-alpine-perl.template
Dockerfile-alpine-slim.template
Dockerfile-alpine.template
Dockerfile-debian-otel.template
Dockerfile-debian-perl.template
Dockerfile-debian.template
mainline/alpine-otel/Dockerfile
mainline/alpine-perl/Dockerfile
mainline/alpine-slim/Dockerfile
mainline/alpine/Dockerfile
mainline/debian-otel/Dockerfile
mainline/debian-perl/Dockerfile
mainline/debian/Dockerfile
modules/Dockerfile
modules/Dockerfile.alpine
modules/README.md
stable/alpine-otel/Dockerfile
stable/alpine-perl/Dockerfile
stable/alpine-slim/Dockerfile
stable/alpine/Dockerfile
stable/debian-otel/Dockerfile
stable/debian-perl/Dockerfile
stable/debian/Dockerfile
update.sh

A few commits to fetch NGINX packaging sources from github instead of a discontinued mercurial repo.

Adapt for NGINX packaging move to GitHub

---

mainline/alpine-otel/Dockerfile
mainline/alpine-perl/Dockerfile
mainline/alpine-slim/Dockerfile
mainline/alpine/Dockerfile
mainline/debian-otel/Dockerfile
mainline/debian-perl/Dockerfile
mainline/debian/Dockerfile
update.sh

Updated mainline nginx to 1.27.3 and njs to 0.8.7.

Updated mainline nginx to 1.27.3.

---

generate-stackbrew-library.sh

Since riscv64 had be adopted in alpine 3.20 (stable, released in May 22), we can add riscv64 and update alpine.

Add riscv64 support

---

.github/workflows/sync.yml

This CI job adds a periodic (and a manual) way to sync current Docker Hub images to a Public AWS ECR registry owned by nginx.

Added a CI job to sync images to AWS ECR Public.

---

mainline/alpine-slim/Dockerfile
update.sh

Updates the mainline image to use Alpine 3.21 as default version. See also https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.21.0.
This first requires the Alpine 3.21 base image to appear; see also https://github.com/docker-library/official-images/pull/18024.
Note: given that this requires built binaries for the new Alpine version and won't take any effect until an actual new release of `nginx` itself, this PR is intentionally marked as draft, so it can function both as a heads-up about the new release (in anticipation of new mainline release that will probably appear soon?) and a place that allows for subscription to any potential updates. It can then be merged later at any convenient time when everything is ready. However, if it is still preferable to close this in the …

Update mainline to Alpine 3.21

---

modules/Dockerfile
modules/Dockerfile.alpine

Docker complains about FROM ${NGINX_FROM_IMAGE} as builder because `'as' and 'FROM' keywords' casing do not match` [info](https://docs.docker.com/reference/build-checks/from-as-casing/).
Super simple fix. Absolutely a minor fix, but it's one less warning.

Fix FromAsCasing warning

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md
SUPPORT.md
generate-stackbrew-library.sh
modules/README.md

Change the mentions of nginxinc org everywhere following the repo transfer to nginx org.

Change the org following the repo transfer to nginx namespace.

---

Dockerfile-alpine-slim.template
mainline/alpine-slim/Dockerfile
stable/alpine-slim/Dockerfile

As of Alpine v3.18 the `envsubst` command has been split out into it's own package (`gettext-envsubst`), so the workaround to extract it from the `gettext` package is no longer required.
https://pkgs.alpinelinux.org/packages?name=gettext-envsubst&branch=v3.18
I just intended to create this PR as a quick edit while I was working on something else instead of creating a ticket. I see that there's more steps required for PRs and I can come back at some point and complete the rest of the steps, or someone else is welcome to reuse/complete this!

chore: use gettext-envsubst alpine package instead of workaround

---

stable/alpine-slim/Dockerfile
update.sh

This is a follow-up to #948, given that in my eyes it seems most likely a new mainline release will precede a new stable release.
Updates the stable image to use Alpine 3.21 as default version. See also https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.21.0.
Note: given that this requires built binaries for the new Alpine version and won't take any effect until an actual new release of `nginx` itself, this PR is intentionally marked as draft, so it can function both as a heads-up about the new release and a place that allows for subscription to any potential updates. It can then be merged later at any convenient time when everything is ready. However, if it is still preferable to close this in the meantime, feel free to do so.
Modelled after #895.
Before creating a PR, run …

Update stable to Alpine 3.21

---

generate-stackbrew-library.sh
stable/alpine-otel/Dockerfile
stable/alpine-perl/Dockerfile
stable/alpine-slim/Dockerfile
stable/alpine/Dockerfile
stable/debian-otel/Dockerfile
stable/debian-perl/Dockerfile
stable/debian/Dockerfile
sync-awsecr.sh
update.sh

Updated stable nginx to 1.28.0

Updated stable nginx to 1.28.0

---

Dockerfile-debian.template
mainline/debian/Dockerfile
stable/debian/Dockerfile

This makes sure all keys are exported to a keyring archive, as opposed to only the first key.

Pass GPG key ids as separate arguments when exporting.
