nginx/docker-nginx

- Dockerfile
```console
$ curl -fsSL 'http://nginx.org/packages/mainline/debian/dists/jessie/nginx/binary-amd64/Packages' \
| awk -F ': ' '$1 == "Package" { pkg = $2 } pkg == "nginx" && $1 == "Version" { print $2 }' \
| sort -V | tail -1
```
Fixes #25
> Bump to 1.9.1-1~jessie

- Dockerfile
2015-07-14 nginx-1.9.3 mainline version has been released.
> Bump to 1.9.3-1~jessie

- Dockerfile
> update to 1.9.4

- Dockerfile
> Upgrade to 1.9.5

- Dockerfile
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>
> Rejig the Dockerfile to reduce the number of small layers

- mainline/alpine-perl/Dockerfile
- mainline/alpine/Dockerfile
- mainline/stretch-perl/Dockerfile
- mainline/stretch/Dockerfile
- stable/alpine-perl/Dockerfile
- stable/alpine/Dockerfile
- stable/stretch-perl/Dockerfile
- stable/stretch/Dockerfile
Replace maintainer instruction by label instruction
> Maintainer instruction is deprecated

- mainline/alpine-perl/Dockerfile
- mainline/alpine/Dockerfile
- stable/alpine-perl/Dockerfile
- stable/alpine/Dockerfile
> Remove dash from su command

- generate-stackbrew-library.sh
- stable/alpine-perl/Dockerfile
- stable/alpine/Dockerfile
- stable/buster-perl/Dockerfile
- stable/buster/Dockerfile
nginx 1.16.1 => 1.18.0
njs 0.3.8 => 0.3.9
alpine 3.10 => 3.11
🎉
> Updated stable nginx to 1.18.0

- mainline/alpine-perl/Dockerfile
- mainline/alpine/Dockerfile
- mainline/buster-perl/Dockerfile
- mainline/buster/Dockerfile
Updates:
Nginx: 1.19.3
NJS: 0.4.4
Fixes #453
> Update Nginx version to 1.19.3

- mainline/alpine-perl/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- update.sh
nginx 1.21.1 => 1.21.2
njs 0.6.1 => 0.6.2
🎉
> Updated mainline nginx and njs

- mainline/alpine-perl/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- stable/alpine-perl/Dockerfile
- stable/alpine/Dockerfile
- update.sh
Updating nginx to 1.21.4 and njs to 0.7.0
> Update nginx mainline to 1.21.4, njs to 0.7.0

- mainline/alpine-perl/Dockerfile
- mainline/alpine/Dockerfile
- update.sh
Updates Alpine to 3.15 for mainline.
> Update mainline base image to Alpine 3.15

- mainline/alpine-perl/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- update.sh
Updates nginx and njs to the latest version.
> Update nginx mainline to 1.21.5, njs to 0.7.1

- generate-stackbrew-library.sh
Refs https://github.com/nginxinc/docker-nginx/issues/649
> Added distribution versions to generated tags.

- entrypoint/20-envsubst-on-templates.sh
- mainline/alpine-perl/Dockerfile
- mainline/alpine-slim/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- update.sh
Updates nginx to `1.25.0` and njs to `0.7.12` for mainline
> Bump NGINX mainline to 1.25.0, NJS to 0.7.12

- mainline/alpine-slim/Dockerfile
- stable/alpine-slim/Dockerfile
- update.sh
Fixes https://github.com/nginxinc/docker-nginx/issues/792
> Updated Alpine to 3.18

- mainline/alpine-perl/Dockerfile
- mainline/alpine-slim/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian/Dockerfile
- stable/alpine-perl/Dockerfile
- stable/alpine-slim/Dockerfile
- stable/alpine/Dockerfile
- stable/debian/Dockerfile
- update.sh
Closes https://github.com/nginxinc/docker-nginx/issues/809
> Updated njs to 0.8.0.

- .test/config.sh
- .test/tests/modules/nginx.conf.sme
- .test/tests/modules/run.sh
- modules/Dockerfile
- modules/Dockerfile.alpine
- modules/README.md
Added a test in github CI to actually check if proposed changes are fine.
While at it, fixed the modules Dockerfiles to enable providing base image.
> modules-related improvements

- mainline/alpine-perl/Dockerfile
- mainline/alpine-slim/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- update.sh
Update mainline NGINX to 1.25.2.
> Updated mainline nginx to 1.25.2.

- mainline/alpine-perl/Dockerfile
- mainline/alpine-slim/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- update.sh
Updated mainline nginx to 1.25.3 and njs to 0.8.2.
> Updated mainline nginx to 1.25.3 and njs to 0.8.2.

- Dockerfile-debian-otel.template
- Dockerfile-debian-perl.template
- mainline/debian-otel/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- stable/debian-otel/Dockerfile
- stable/debian-perl/Dockerfile
- stable/debian/Dockerfile
> Updated dockerfiles after 23bcf128302

- generate-stackbrew-library.sh
- mainline/alpine-otel/Dockerfile
- mainline/alpine-perl/Dockerfile
- mainline/alpine-slim/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-otel/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- stable/alpine-otel/Dockerfile
- stable/alpine-perl/Dockerfile
- stable/alpine-slim/Dockerfile
- stable/alpine/Dockerfile
- stable/debian-otel/Dockerfile
- stable/debian-perl/Dockerfile
- stable/debian/Dockerfile
- sync-awsecr.sh
- update.sh
Update nginx versions to 1.26.1 and 1.27.0
> Updated nginx versions to 1.26.1 and 1.27.0

- mainline/alpine-otel/Dockerfile
- mainline/alpine-perl/Dockerfile
- mainline/alpine-slim/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-otel/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- update.sh
Update dockerfiles for the 1.27.2 (mainline) nginx release
> Updated mainline to 1.27.2.

- mainline/alpine-otel/Dockerfile
- mainline/alpine-perl/Dockerfile
- mainline/alpine-slim/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-otel/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- stable/alpine-otel/Dockerfile
- stable/alpine-perl/Dockerfile
- stable/alpine-slim/Dockerfile
- stable/alpine/Dockerfile
- stable/debian-otel/Dockerfile
- stable/debian-perl/Dockerfile
- stable/debian/Dockerfile
- update.sh
This PR updates njs to 0.8.8, fixing a number of issues found in previous releases.
> Update njs to 0.8.8

- modules/Dockerfile.alpine
> rm mercurial cause it's replaced by git

- Dockerfile-alpine-otel.template
- mainline/alpine-otel/Dockerfile
- mainline/alpine-perl/Dockerfile
- mainline/alpine-slim/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-otel/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- stable/alpine-otel/Dockerfile
- stable/alpine-perl/Dockerfile
- stable/alpine-slim/Dockerfile
- stable/alpine/Dockerfile
- stable/debian-otel/Dockerfile
- stable/debian-perl/Dockerfile
- stable/debian/Dockerfile
- update.sh
Updates nginx to 1.26.3 and 1.27.4, as well as bumps otel and njs. 
> Update nginx to recent versions & more

- modules/README.md
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
> Fix a small typo in the modules README

- modules/echo/source
Bump echo-nginx-module from 0.62 to 0.63
> Bump echo-nginx-module from 0.62 to 0.63

- .github/workflows/f5_cla.yml
This PR adds the F5 CLA required for all OSS projects moving forward.
> feat: Add F5 CLA workflow

- modules/README.md
Updates the current list of modules.
> modules/README.md: updated the current list of modules.

- Dockerfile-debian.template
Suggested-by: https://github.com/docker-library/official-images/pull/19467#issuecomment-3071271603
> gpg: use --batch for all invocations.

- mainline/alpine-otel/Dockerfile
- mainline/alpine-perl/Dockerfile
- mainline/alpine-slim/Dockerfile
- mainline/alpine/Dockerfile
- mainline/debian-otel/Dockerfile
- mainline/debian-perl/Dockerfile
- mainline/debian/Dockerfile
- update.sh
This PR updates nginx mainline to 1.29.1 and njs to 0.9.1.
> Updated nginx mainline to 1.29.1 and njs to 0.9.1.
